name: Build kube-agent

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'

      - name: Build Image
        run: |
          make -C cmd/kube-agent build

      - name: Push Image
        if: ${{ github.event_name == 'push' }}
        run: |-
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          test "$GITHUB_REF_NAME" = master && \
            make -C cmd/kube-agent push TAG=latest || \
            make -C cmd/kube-agent push TAG="$GITHUB_REF_NAME"
